package Biblio::Citation::Parser::Templates;

######################################################################
#
# Biblio::Citation::Parser::Templates;
#
######################################################################
#
#  This file is part of ParaCite Tools (http://paracite.eprints.org/developers/)
#
#  Copyright (c) 2004 University of Southampton, UK. SO17 1BJ.
#
#  ParaTools is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  ParaTools is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with ParaTools; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
######################################################################


=pod

=head1 NAME

Biblio::Citation::Parser::Templates - citation templates collection

=head1 DESCRIPTION

This package contains a list of templates that are
used to parse citations. Updates will be made available at
http://paracite.eprints.org/developers/ (hopefully with a merging tool to
ensure you don't lose any changes). To add new fields, edit Standard.pm.

=cut

$Biblio::Citation::Parser::Templates::templates = [

	# PROSIDING, WORKSHOP
	'prosiding=>_AUTHORS_. _YEAR_. _TITLE_. Proceedings of _PUBLOC_. _PUBLISHER_.',
	'prosiding=>_AUTHORS_. _YEAR_. _TITLE_. Proceedings of _PUBLISHER_. ISSN _ISSN_.',
	'prosiding=>_AUTHORS_. _YEAR_. _TITLE_. Proceedings of _PUBLISHER_ Workshop on _PUBLOC_. _PAGES_.',
	'prosiding=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_ Workshop on _PUBLOC_. _PAGES_.',
	'prosiding=>_AUTHORS_. _YEAR_. _TITLE_. Prosiding _PUBLOC_. _PUBLISHER_.',
	'prosiding=>_AUTHORS_. _YEAR_. _TITLE_. Prosiding _PUBLISHER_. ISSN _ISSN_.',
	'prosiding=>_AUTHORS_. _YEAR_. _TITLE_. Prosiding _PUBLISHER_ Seminar _PUBLOC_. _PAGES_.',
	'prosiding=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_ Seminar _PUBLOC_. _PAGES_.',


	'prosiding=>_AUTHORS_. _YEAR_a. _TITLE_. Proceedings of _PUBLOC_. _PUBLISHER_.',
	'prosiding=>_AUTHORS_. _YEAR_a. _TITLE_. Proceedings of _PUBLISHER_. ISSN _ISSN_.',
	'prosiding=>_AUTHORS_. _YEAR_a. _TITLE_. Proceedings of _PUBLISHER_ Workshop on _PUBLOC_. _PAGES_.',
	'prosiding=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_ Workshop on _PUBLOC_. _PAGES_.',
	'prosiding=>_AUTHORS_. _YEAR_a. _TITLE_. Prosiding _PUBLOC_. _PUBLISHER_.',
	'prosiding=>_AUTHORS_. _YEAR_a. _TITLE_. Prosiding _PUBLISHER_. ISSN _ISSN_.',
	'prosiding=>_AUTHORS_. _YEAR_a. _TITLE_. Prosiding _PUBLISHER_ Seminar _PUBLOC_. _PAGES_.',
	'prosiding=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_ Seminar _PUBLOC_. _PAGES_.',

	'prosiding=>_AUTHORS_. _YEAR_b. _TITLE_. Proceedings of _PUBLOC_. _PUBLISHER_.',
	'prosiding=>_AUTHORS_. _YEAR_b. _TITLE_. Proceedings of _PUBLISHER_. ISSN _ISSN_.',
	'prosiding=>_AUTHORS_. _YEAR_b. _TITLE_. Proceedings of _PUBLISHER_ Workshop on _PUBLOC_. _PAGES_.',
	'prosiding=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_ Workshop on _PUBLOC_. _PAGES_.',
	'prosiding=>_AUTHORS_. _YEAR_b. _TITLE_. Prosiding _PUBLOC_. _PUBLISHER_.',
	'prosiding=>_AUTHORS_. _YEAR_b. _TITLE_. Prosiding _PUBLISHER_. ISSN _ISSN_.',
	'prosiding=>_AUTHORS_. _YEAR_b. _TITLE_. Prosiding _PUBLISHER_ Seminar _PUBLOC_. _PAGES_.',
	'prosiding=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_ Seminar _PUBLOC_. _PAGES_.',

	'prosiding=>_AUTHORS_. _YEAR_c. _TITLE_. Proceedings of _PUBLOC_. _PUBLISHER_.',
	'prosiding=>_AUTHORS_. _YEAR_c. _TITLE_. Proceedings of _PUBLISHER_. ISSN _ISSN_.',
	'prosiding=>_AUTHORS_. _YEAR_c. _TITLE_. Proceedings of _PUBLISHER_ Workshop on _PUBLOC_. _PAGES_.',
	'prosiding=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_ Workshop on _PUBLOC_. _PAGES_.',
	'prosiding=>_AUTHORS_. _YEAR_c. _TITLE_. Prosiding _PUBLOC_. _PUBLISHER_.',
	'prosiding=>_AUTHORS_. _YEAR_c. _TITLE_. Prosiding _PUBLISHER_. ISSN _ISSN_.',
	'prosiding=>_AUTHORS_. _YEAR_c. _TITLE_. Prosiding _PUBLISHER_ Seminar _PUBLOC_. _PAGES_.',
	'prosiding=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_ Seminar _PUBLOC_. _PAGES_.',

	'prosiding=>_AUTHORS_. _YEAR_d. _TITLE_. Proceedings of _PUBLOC_. _PUBLISHER_.',
	'prosiding=>_AUTHORS_. _YEAR_d. _TITLE_. Proceedings of _PUBLISHER_. ISSN _ISSN_.',
	'prosiding=>_AUTHORS_. _YEAR_d. _TITLE_. Proceedings of _PUBLISHER_ Workshop on _PUBLOC_. _PAGES_.',
	'prosiding=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_ Workshop on _PUBLOC_. _PAGES_.',
	'prosiding=>_AUTHORS_. _YEAR_d. _TITLE_. Prosiding _PUBLOC_. _PUBLISHER_.',
	'prosiding=>_AUTHORS_. _YEAR_d. _TITLE_. Prosiding _PUBLISHER_. ISSN _ISSN_.',
	'prosiding=>_AUTHORS_. _YEAR_d. _TITLE_. Prosiding _PUBLISHER_ Seminar _PUBLOC_. _PAGES_.',
	'prosiding=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_ Seminar _PUBLOC_. _PAGES_.',


	#MAKALAH, JOURNAL
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Journal of _PUBLISHER_. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Journal of _PUBLISHER_. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Journal of _PUBLISHER_. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Journal of _PUBLISHER_. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: Vol. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_: Vol. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, Vol. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, Vol. _PAGES_.',



	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Journal of _PUBLISHER_. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Journal of _PUBLISHER_. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Journal of _PUBLISHER_. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Journal of _PUBLISHER_. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_: Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_: Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_: Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_: Vol. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_: _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_: _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_: _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_: _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_: _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_: _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_: _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, Vol. _PAGES_.',

	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Journal of _PUBLISHER_. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Journal of _PUBLISHER_. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Journal of _PUBLISHER_. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Journal of _PUBLISHER_. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_: Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_: Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_: Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_: Vol. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_: _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_: _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_: _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_: _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_: _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_: _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_: _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, Vol. _PAGES_.',

	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Journal of _PUBLISHER_. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Journal of _PUBLISHER_. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Journal of _PUBLISHER_. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Journal of _PUBLISHER_. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_: Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_: Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_: Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_: Vol. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_: _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_: _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_: _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_: _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_: _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_: _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_: _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, Vol. _PAGES_.',


	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Journal of _PUBLISHER_. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Journal of _PUBLISHER_. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Journal of _PUBLISHER_. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Journal of _PUBLISHER_. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Technical Report, _PUBLISHER_. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Journal of _PUBLISHER_. Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. Technical Report, _PUBLISHER_. Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_: Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_: Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_: Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_: Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_: Vol. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_: _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_: _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_: _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_: _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_: _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_: _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_: _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_):_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_). _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_(_ISSUE_).',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_. _PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_:_PAGES_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _VOLUME_.',
	'jurnal=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, Vol. _PAGES_.',

	#SKRIPSI, TESIS, DISERTASI
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_ [skripsi]. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_ [skripsi]. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_ [tesis]. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_ [tesis]. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_ [disertasi]. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_ [disertasi]. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_ [skripsi]. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_ [skripsi]. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_ [tesis]. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_ [tesis]. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_ [disertasi]. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_ [disertasi]. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_. Skripsi. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_. Skripsi. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_. Tesis. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_. Tesis. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_. Disertasi. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_. Disertasi. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_. Skripsi. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_. Skripsi. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_. Tesis. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_. Tesis. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_. Disertasi. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_. Disertasi. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_.  _ANY_ disertation, _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_.  _ANY_ disertation, _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_. _TITLE_.  _ANY_ disertation, _PUBLISHER_, _PUBLOC_.',

	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_ [skripsi]. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_ [skripsi]. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_ [tesis]. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_ [tesis]. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_ [disertasi]. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_ [disertasi]. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_ [skripsi]. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_ [skripsi]. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_ [tesis]. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_ [tesis]. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_ [disertasi]. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_ [disertasi]. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_. Skripsi. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_. Skripsi. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_. Tesis. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_. Tesis. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_. Disertasi. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_. Disertasi. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_. Skripsi. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_. Skripsi. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_. Tesis. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_. Tesis. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_. Disertasi. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_. Disertasi. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_.  _ANY_ disertation, _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_.  _ANY_ disertation, _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_a. _TITLE_.  _ANY_ disertation, _PUBLISHER_, _PUBLOC_.',

	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_ [skripsi]. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_ [skripsi]. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_ [tesis]. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_ [tesis]. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_ [disertasi]. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_ [disertasi]. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_ [skripsi]. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_ [skripsi]. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_ [tesis]. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_ [tesis]. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_ [disertasi]. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_ [disertasi]. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_. Skripsi. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_. Skripsi. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_. Tesis. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_. Tesis. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_. Disertasi. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_. Disertasi. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_. Skripsi. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_. Skripsi. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_. Tesis. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_. Tesis. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_. Disertasi. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_. Disertasi. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_.  _ANY_ disertation, _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_.  _ANY_ disertation, _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_b. _TITLE_.  _ANY_ disertation, _PUBLISHER_, _PUBLOC_.',

	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_ [skripsi]. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_ [skripsi]. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_ [tesis]. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_ [tesis]. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_ [disertasi]. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_ [disertasi]. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_ [skripsi]. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_ [skripsi]. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_ [tesis]. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_ [tesis]. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_ [disertasi]. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_ [disertasi]. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_. Skripsi. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_. Skripsi. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_. Tesis. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_. Tesis. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_. Disertasi. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_. Disertasi. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_. Skripsi. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_. Skripsi. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_. Tesis. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_. Tesis. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_. Disertasi. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_. Disertasi. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_.  _ANY_ disertation, _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_.  _ANY_ disertation, _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_c. _TITLE_.  _ANY_ disertation, _PUBLISHER_, _PUBLOC_.',		

	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_ [skripsi]. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_ [skripsi]. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_ [tesis]. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_ [tesis]. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_ [disertasi]. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_ [disertasi]. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_ [skripsi]. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_ [skripsi]. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_ [tesis]. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_ [tesis]. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_ [disertasi]. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_ [disertasi]. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_. Skripsi. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_. Skripsi. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_. Tesis. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_. Tesis. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_. Disertasi. _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_. Disertasi. _PUBLOC_: _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_. Skripsi. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_. Skripsi. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_. Tesis. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_. Tesis. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_. Disertasi. _PUBLISHER_, _PUBLOC_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_. Disertasi. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_.  _ANY_ disertation, _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_.  _ANY_ disertation, _PUBLOC_. _PUBLISHER_.',
	'skripsi=>_AUTHORS_. _YEAR_d. _TITLE_.  _ANY_ disertation, _PUBLISHER_, _PUBLOC_.',		

	#WEBSITE 
	'website=>_AUTHORS_. _YEAR_. _TITLE_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_, _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_. _TITLE_. _ANY_ disertation, _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_. _TITLE_. _URL_',

	'website=>_AUTHORS_. _YEAR_a. _TITLE_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_, _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_a. _TITLE_. _ANY_ disertation, _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_a. _TITLE_. _URL_',

	'website=>_AUTHORS_. _YEAR_b. _TITLE_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_, _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_b. _TITLE_. _ANY_ disertation, _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_b. _TITLE_. _URL_',

	'website=>_AUTHORS_. _YEAR_c. _TITLE_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_, _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_c. _TITLE_. _ANY_ disertation, _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_c. _TITLE_. _URL_',

	'website=>_AUTHORS_. _YEAR_d. _TITLE_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_, _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_d. _TITLE_. _ANY_ disertation, _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _YEAR_d. _TITLE_. _URL_',

	'website=>_AUTHORS_. _TITLE_. _PUBLISHER_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _TITLE_. _PUBLOC_ _URL_ [_ANY_]',
	'website=>_AUTHORS_. _TITLE_. _ANY_ disertation, _PUBLOC_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _TITLE_. _URL_ [_ANY_]',
	'website=>_AUTHORS_. _TITLE_. disertation, _PUBLOC_. _URL_ [_ANY_]',

	#BUKU
	'buku=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLICATION_. _PUBLISHER_.',
	'buku=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLICATION_. _PUBLISHER_, _PUBLOC_.',
	'buku=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_. _PUBLOC_.',
	'buku=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLOC_:_PUBLISHER_.',
	'buku=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_. _PAGES_.',
	'buku=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_. _ANY_.',
	'buku=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_.',
	'buku=>_AUTHORS_. _YEAR_. _TITLE_. _PUBLISHER_. _PUBLOC_.',	
	'buku=>_AUTHORS_. _YEAR_. _TITLE_.',

	'buku=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLICATION_. _PUBLISHER_.',
	'buku=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLICATION_. _PUBLISHER_, _PUBLOC_.',
	'buku=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_. _PUBLOC_.',
	'buku=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLOC_:_PUBLISHER_.',
	'buku=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_. _PAGES_.',
	'buku=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_. _ANY_.',
	'buku=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_.',
	'buku=>_AUTHORS_. _YEAR_a. _TITLE_. _PUBLISHER_. _PUBLOC_.',	
	'buku=>_AUTHORS_. _YEAR_a. _TITLE_.',

	'buku=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLICATION_. _PUBLISHER_.',
	'buku=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLICATION_. _PUBLISHER_, _PUBLOC_.',
	'buku=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_. _PUBLOC_.',
	'buku=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLOC_:_PUBLISHER_.',
	'buku=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_. _PAGES_.',
	'buku=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_. _ANY_.',
	'buku=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_.',
	'buku=>_AUTHORS_. _YEAR_b. _TITLE_. _PUBLISHER_. _PUBLOC_.',	
	'buku=>_AUTHORS_. _YEAR_b. _TITLE_.',

	'buku=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLICATION_. _PUBLISHER_.',
	'buku=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLICATION_. _PUBLISHER_, _PUBLOC_.',
	'buku=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_. _PUBLOC_.',
	'buku=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLOC_:_PUBLISHER_.',
	'buku=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_. _PAGES_.',
	'buku=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_. _ANY_.',
	'buku=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_.',
	'buku=>_AUTHORS_. _YEAR_c. _TITLE_. _PUBLISHER_. _PUBLOC_.',	
	'buku=>_AUTHORS_. _YEAR_c. _TITLE_.',

	'buku=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLICATION_. _PUBLISHER_.',
	'buku=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLICATION_. _PUBLISHER_, _PUBLOC_.',
	'buku=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_. _PUBLOC_.',
	'buku=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLOC_:_PUBLISHER_.',
	'buku=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_. _PAGES_.',
	'buku=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_. _ANY_.',
	'buku=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_.',
	'buku=>_AUTHORS_. _YEAR_d. _TITLE_. _PUBLISHER_. _PUBLOC_.',	
	'buku=>_AUTHORS_. _YEAR_d. _TITLE_.',
	#MISC
	'misc=>_AUTHORS_. _TITLE_. _PUBLICATION_. _PUBLISHER_.',
	'misc=>_AUTHORS_. _TITLE_. _PUBLICATION_. _PUBLISHER_. _PUBLOC_.',
	'misc=>_AUTHORS_. _TITLE_. _PUBLISHER_. _PUBLOC_.',
	'misc=>_AUTHORS_. _TITLE_. _PUBLOC_:_PUBLISHER_.',


	'misc=>_AUTHORS_. _TITLE_. _PUBLISHER_. _PAGES_.',
	'misc=>_AUTHORS_. _TITLE_. _PUBLISHER_. _ANY_.',

	'misc=>_AUTHORS_. _TITLE_. _PUBLISHER_.',
	'misc=>_AUTHORS_. _TITLE_. _PUBLISHER_. _PUBLOC_.',	
	'misc=>_AUTHORS_. _TITLE_.'

];

1;


__END__

=pod

=head1 AUTHOR

Mike Jewell <moj@ecs.soton.ac.uk>

=cut
