<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>{$_TITLE}</title>
    {include file="ext-cssmain.htm"}
	<link rel="stylesheet" type="text/css" href="{$_URL}/css/app.css">	
	{include file="ext-jsmain.htm"}
	<script type="text/javascript" src="{$_URL}/js/app/Home.js"></script>
</head>
<body>
</body>
</html>