<div id="footer">    
	<div class="row-fluid">
		<div class="container footer_columns_container"> 	
			<div class="row some_padding footer_bottom">
				<div class="span12">
					<div id="copyright_blurb" class="copyright_blurb">Copyright © 2013 Institut Pertanian Bogor</div>
					<div class="copyright_blurb">Sebuah tesis yang dibuat oleh Firnas Nadirman</div>
				</div>
			</div>
		</div>
	</div>
</div>
  <div id="wrapper"></div>
</body>
</html>