<!DOCTYPE html>
<html class="wf-opensans-n6-active wf-opensans-n4-active wf-opensans-n3-active wf-active" lang="en">
<head>
    <meta charset="utf-8"> 
    <title>{$_TITLE}</title> 
    <link href="assets/css/normalize.css" rel="stylesheet">
    <link href="assets/css/style.css" rel="stylesheet">
    <link href="assets/css/bootstrap.css" rel="stylesheet">
    <link href="assets/css/font.css" rel="stylesheet">
	<script type="text/javascript" src="{$_URL}/assets/js/jquery-1.9.1.min.js"></script>	
	<script type="text/javascript" src="{$_URL}/assets/js/jit-yc.js"></script>	
    <script type="text/javascript" src="{$_URL}/assets/js/tkidp.js"></script>   
 	<script type="text/javascript" src="{$_URL}/assets/js/main.js"></script>	
</head>
<body>
<div style="position:absolute;bottom:0;right:0;width:0;height:0;overflow:hidden;"></div>